spring.application.name=RegionKommuneE25A

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/regionkommunee25a
spring.datasource.username=jens
spring.datasource.password=x

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

